# site: tuscaloosa
# area: tsc
# category: apa | apartments / housing for rent	
site: nashville
area: apa
url: 'https://tuscaloosa.craigslist.com/'
category: rts # real estate services
filters:
  max_price: 1200
  private_room: True
